/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.PrintWriter;
import java.io.UnsupportedEncodingException;
import java.util.logging.Level;
import java.util.logging.Logger;


/**
 *
 * @author reine
 */

public class JFrame2 extends javax.swing.JFrame {

    /**
     * Creates new form JFrame2
     */
    public JFrame2() {
        initComponents();
        drinkConfirm.setText("Beverage: " + JFrame1.drinkSet.getText());
        breadConfirm.setText("Sub Bread: " + JFrame1.breadSet.getText());
        typeConfirm.setText("Sub Type: " + JFrame1.typeSet.getText());
        sizeConfirm.setText("Sub Size: " + JFrame1.sizeSet.getText());
        nameConfirm.setText("Name: " + JFrame1.nameSet.getText());
        addressConfirm.setText("Address: " + JFrame1.addressSet.getText());
        cityConfirm.setText("City: " + JFrame1.citySet.getText());
        stateConfirm.setText("State: " + JFrame1.stateSet.getText());
        zipConfirm.setText("Zip Code: " + JFrame1.zipSet.getText());
        phoneConfirm.setText("Phone: " + JFrame1.phoneSet.getText());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        drinkConfirm = new javax.swing.JLabel();
        breadConfirm = new javax.swing.JLabel();
        typeConfirm = new javax.swing.JLabel();
        sizeConfirm = new javax.swing.JLabel();
        nameConfirm = new javax.swing.JLabel();
        addressConfirm = new javax.swing.JLabel();
        cityConfirm = new javax.swing.JLabel();
        stateConfirm = new javax.swing.JLabel();
        zipConfirm = new javax.swing.JLabel();
        phoneConfirm = new javax.swing.JLabel();
        button1 = new java.awt.Button();
        Cancel = new java.awt.Button();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("***FAVORITE FAMOUS SUBS***");
        setMinimumSize(new java.awt.Dimension(60, 40));

        drinkConfirm.setText("jLabel1");

        breadConfirm.setText("jLabel1");

        typeConfirm.setText("jLabel1");

        sizeConfirm.setText("jLabel1");

        nameConfirm.setText("jLabel1");

        addressConfirm.setText("jLabel1");

        cityConfirm.setText("jLabel1");

        stateConfirm.setText("jLabel1");

        zipConfirm.setText("jLabel1");

        phoneConfirm.setText("jLabel1");

        button1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        button1.setLabel("Confirm Order");
        button1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button1MouseClicked(evt);
            }
        });
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });

        Cancel.setActionCommand("Cancel");
        Cancel.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        Cancel.setLabel("Cancel");
        Cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CancelMousePressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Order Details");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Customer Information");

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jSeparator1.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(59, 59, 59)
                                .addComponent(Cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(phoneConfirm)
                            .addComponent(addressConfirm)
                            .addComponent(nameConfirm)
                            .addComponent(sizeConfirm)
                            .addComponent(typeConfirm)
                            .addComponent(breadConfirm)
                            .addComponent(drinkConfirm)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cityConfirm)
                                .addGap(18, 18, 18)
                                .addComponent(stateConfirm)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(zipConfirm))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(drinkConfirm)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(breadConfirm)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(typeConfirm)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sizeConfirm)
                .addGap(13, 13, 13)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nameConfirm)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addressConfirm)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cityConfirm)
                    .addComponent(stateConfirm)
                    .addComponent(zipConfirm))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(phoneConfirm)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Cancel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_button1MouseClicked

    private void CancelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelMousePressed
        System.exit(0);
    }//GEN-LAST:event_CancelMousePressed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        JFrame3 confirm2 = new JFrame3();
        confirm2.setVisible(true);
        try (PrintWriter writer = new PrintWriter("SubOrder.txt", "UTF-8")) {
            writer.println("Thank you " + JFrame1.nameSet.getText() + "\n" + "for choosing Famous Favorite Subs!");
            writer.println("Your order of a " + JFrame1.drinkSet.getText() + " with a " + JFrame1.sizeSet.getText() + " " + JFrame1.typeSet.getText() + " sub on " + JFrame1.breadSet.getText() + " bread");
            writer.println("will be delivered to the address " + JFrame1.addressSet.getText() + ", " + JFrame1.citySet.getText() + ", " + JFrame1.stateSet.getText() + ", " + JFrame1.zipSet.getText() + ".");
            writer.println("Your phone number is " + JFrame1.phoneSet.getText() + ".");
        } catch (FileNotFoundException | UnsupportedEncodingException ex) {
            Logger.getLogger(JFrame2.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_button1ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button Cancel;
    private javax.swing.JLabel addressConfirm;
    private javax.swing.JLabel breadConfirm;
    private java.awt.Button button1;
    private javax.swing.JLabel cityConfirm;
    private javax.swing.JLabel drinkConfirm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel nameConfirm;
    private javax.swing.JLabel phoneConfirm;
    private javax.swing.JLabel sizeConfirm;
    private javax.swing.JLabel stateConfirm;
    private javax.swing.JLabel typeConfirm;
    private javax.swing.JLabel zipConfirm;
    // End of variables declaration//GEN-END:variables
}

